from . import hotel_management
from . import rooms_types
from . import rooms_facility
from . import add_hotel
from . import room_floor
from . import rooms
from . import customer
from . import staff
from . import tags
from . import amenities
from . import policy_template
from . import policy
from . import generate_room_wizard
from . import hotel_booking
from . import transport_services
from . import pickup_destination_location
from . import transport_mode
from . import inquiry_mode
from . import hotel_booking_room_line
from . import hotel_booking_guest
from . import lead_inquiry
from . import seasonable_price
from . import send_email_wizard
from . import account_move_inherit